---
name: stdout

releases:
  - name: stdout
    version: latest
  - name: bats
    version: latest
  - name: bash_shell_mock
    version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
  
stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

instance_groups:
  - name: stdout
    azs: [z1, z2, z3]
    instances: 1
    vm_type: default
    stemcell: default
    persistent_disk: 10240
    networks:
      - name: default
    jobs:
      - name: main
        release: stdout
        provides: {}
        properties: 
          strings:
            message: we are inside
      - name: run_bats
        release: bats
        properties:
          test_location: '/var/vcap/packages/bats/main_test.sh'
      - name: install_bash_shell_mock
        release: bash_shell_mock
        properties:
          install_location: '/var/vcap/packages/bats/mock/'
      
      
